-- test-oracle.sql
-- Creates test tables, views, functions & procedures for exercising
-- datum's Oracle introspection features.
--
-- Runs as the DATUM_TEST app user in the FREEPDB1 pluggable database.
-- The gvenzl/oracle-free Docker image auto-creates this user via
-- APP_USER / APP_USER_PASSWORD environment variables.
--
-- Usage:
--   sqlplus datum_test/datum_test@oracle:1521/FREEPDB1 @test-oracle.sql

-- ============================================================
-- Tables
-- ============================================================

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME    VARCHAR2(100) NOT NULL,
    LAST_NAME     VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(255) NULL,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ACTIVE     NUMBER(1) DEFAULT 1,
    CONSTRAINT UQ_CUSTOMERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SKU           VARCHAR2(50) NOT NULL,
    NAME          VARCHAR2(200) NOT NULL,
    DESCRIPTION   CLOB NULL,
    CATEGORY      VARCHAR2(100) NULL,
    UNIT_PRICE    NUMBER(10,2) NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UQ_PRODUCTS_SKU UNIQUE (SKU)
);

CREATE TABLE ORDERS (
    ORDER_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID   NUMBER NOT NULL,
    ORDER_DATE    DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    TOTAL_AMOUNT  NUMBER(12,2) DEFAULT 0 NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'pending',
    CONSTRAINT FK_ORDERS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ORDER_ITEMS (
    ITEM_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID      NUMBER NOT NULL,
    PRODUCT_ID    NUMBER NOT NULL,
    QUANTITY      NUMBER DEFAULT 1 NOT NULL,
    UNIT_PRICE    NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_ITEMS_ORDER
        FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE STOCK_LEVELS (
    STOCK_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID    NUMBER NOT NULL,
    WAREHOUSE     VARCHAR2(100) NOT NULL,
    QUANTITY      NUMBER DEFAULT 0 NOT NULL,
    LAST_UPDATED  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_STOCK_PRODUCT
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(200) NOT NULL,
    CONTACT_EMAIL VARCHAR2(255) NULL,
    PHONE         VARCHAR2(50) NULL,
    COUNTRY       VARCHAR2(100) NULL
);

CREATE TABLE DAILY_SALES (
    REPORT_DATE   DATE PRIMARY KEY,
    TOTAL_ORDERS  NUMBER DEFAULT 0 NOT NULL,
    TOTAL_REVENUE NUMBER(14,2) DEFAULT 0 NOT NULL,
    AVG_ORDER     NUMBER(10,2) NULL
);

CREATE TABLE CUSTOMER_SEGMENTS (
    SEGMENT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SEGMENT_NAME  VARCHAR2(100) NOT NULL,
    MIN_SPEND     NUMBER(12,2) NULL,
    MAX_SPEND     NUMBER(12,2) NULL,
    DESCRIPTION   CLOB NULL
);

-- ============================================================
-- Views
-- ============================================================

CREATE OR REPLACE VIEW CUSTOMER_ORDER_SUMMARY AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS FULL_NAME,
    c.EMAIL,
    COUNT(o.ORDER_ID) AS ORDER_COUNT,
    NVL(SUM(o.TOTAL_AMOUNT), 0) AS LIFETIME_SPEND,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
FROM CUSTOMERS c
LEFT JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL;

CREATE OR REPLACE VIEW LOW_STOCK AS
SELECT
    p.PRODUCT_ID,
    p.SKU,
    p.NAME,
    sl.WAREHOUSE,
    sl.QUANTITY,
    sl.LAST_UPDATED
FROM PRODUCTS p
JOIN STOCK_LEVELS sl ON p.PRODUCT_ID = sl.PRODUCT_ID
WHERE sl.QUANTITY < 10;

CREATE OR REPLACE VIEW REVENUE_BY_CATEGORY AS
SELECT
    p.CATEGORY,
    COUNT(DISTINCT o.ORDER_ID) AS NUM_ORDERS,
    SUM(oi.QUANTITY) AS UNITS_SOLD,
    SUM(oi.QUANTITY * oi.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS oi
JOIN ORDERS o ON oi.ORDER_ID = o.ORDER_ID
JOIN PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY;

-- ============================================================
-- Functions
-- ============================================================

CREATE OR REPLACE FUNCTION FORMAT_CURRENCY(
    P_AMOUNT  IN NUMBER,
    P_SYMBOL  IN VARCHAR2
) RETURN VARCHAR2
IS
BEGIN
    RETURN P_SYMBOL || TO_CHAR(P_AMOUNT, 'FM999,999,990.00');
END FORMAT_CURRENCY;
/

CREATE OR REPLACE FUNCTION IS_VALID_EMAIL(
    P_ADDR IN VARCHAR2
) RETURN NUMBER
IS
BEGIN
    IF REGEXP_LIKE(P_ADDR, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RETURN 1;
    END IF;
    RETURN 0;
END IS_VALID_EMAIL;
/

CREATE OR REPLACE FUNCTION CUSTOMER_LIFETIME_VALUE(
    P_CUSTOMER_ID IN NUMBER
) RETURN NUMBER
IS
    V_TOTAL NUMBER(14,2);
BEGIN
    SELECT NVL(SUM(TOTAL_AMOUNT), 0)
    INTO V_TOTAL
    FROM ORDERS
    WHERE CUSTOMER_ID = P_CUSTOMER_ID;
    RETURN V_TOTAL;
END CUSTOMER_LIFETIME_VALUE;
/

-- ============================================================
-- Procedures
-- ============================================================

CREATE OR REPLACE PROCEDURE DEACTIVATE_CUSTOMER(
    P_CUSTOMER_ID IN NUMBER
)
IS
BEGIN
    UPDATE CUSTOMERS
    SET IS_ACTIVE = 0
    WHERE CUSTOMER_ID = P_CUSTOMER_ID;
END DEACTIVATE_CUSTOMER;
/

CREATE OR REPLACE PROCEDURE PLACE_ORDER(
    P_CUSTOMER_ID IN NUMBER,
    P_PRODUCT_ID  IN NUMBER,
    P_QUANTITY    IN NUMBER,
    P_STATUS      IN VARCHAR2 DEFAULT 'pending'
)
IS
    V_PRICE    NUMBER(10,2);
    V_ORDER_ID NUMBER;
BEGIN
    SELECT UNIT_PRICE INTO V_PRICE
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
    VALUES (P_CUSTOMER_ID, TRUNC(SYSDATE), V_PRICE * P_QUANTITY, P_STATUS)
    RETURNING ORDER_ID INTO V_ORDER_ID;

    INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
    VALUES (V_ORDER_ID, P_PRODUCT_ID, P_QUANTITY, V_PRICE);

    UPDATE STOCK_LEVELS
    SET QUANTITY = QUANTITY - P_QUANTITY,
        LAST_UPDATED = SYSTIMESTAMP
    WHERE PRODUCT_ID = P_PRODUCT_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Product not found');
END PLACE_ORDER;
/

CREATE OR REPLACE PROCEDURE REBUILD_DAILY_SALES(
    P_START_DATE IN DATE,
    P_END_DATE   IN DATE
)
IS
BEGIN
    DELETE FROM DAILY_SALES
    WHERE REPORT_DATE BETWEEN P_START_DATE AND P_END_DATE;

    INSERT INTO DAILY_SALES (REPORT_DATE, TOTAL_ORDERS, TOTAL_REVENUE, AVG_ORDER)
    SELECT
        o.ORDER_DATE,
        COUNT(*),
        SUM(o.TOTAL_AMOUNT),
        AVG(o.TOTAL_AMOUNT)
    FROM ORDERS o
    WHERE o.ORDER_DATE BETWEEN P_START_DATE AND P_END_DATE
    GROUP BY o.ORDER_DATE;
END REBUILD_DAILY_SALES;
/

CREATE OR REPLACE PROCEDURE GET_CUSTOMER_STATS(
    P_CUSTOMER_ID IN  NUMBER,
    P_ORDER_COUNT OUT NUMBER,
    P_TOTAL_SPEND OUT NUMBER
)
IS
BEGIN
    SELECT COUNT(*), NVL(SUM(TOTAL_AMOUNT), 0)
    INTO P_ORDER_COUNT, P_TOTAL_SPEND
    FROM ORDERS
    WHERE CUSTOMER_ID = P_CUSTOMER_ID;
END GET_CUSTOMER_STATS;
/

-- ============================================================
-- Sample data
-- ============================================================

INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Alice', 'Johnson', 'alice@example.com');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Bob', 'Smith', 'bob@example.com');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Carol', 'Williams', 'carol@example.com');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('David', 'Brown', 'david@example.com');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, IS_ACTIVE)
VALUES ('Eve', 'Davis', NULL, 1);

INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, CATEGORY, UNIT_PRICE)
VALUES ('WDG-001', 'Widget A', 'Standard widget', 'Widgets', 9.99);
INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, CATEGORY, UNIT_PRICE)
VALUES ('WDG-002', 'Widget B', 'Premium widget', 'Widgets', 19.99);
INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, CATEGORY, UNIT_PRICE)
VALUES ('GDG-001', 'Gadget X', 'Entry-level gadget', 'Gadgets', 49.99);
INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, CATEGORY, UNIT_PRICE)
VALUES ('GDG-002', 'Gadget Y Pro', 'Professional gadget', 'Gadgets', 99.99);
INSERT INTO PRODUCTS (SKU, NAME, DESCRIPTION, CATEGORY, UNIT_PRICE)
VALUES ('ACC-001', 'Accessory Pack', 'Assorted accessories', 'Accessories', 14.99);

INSERT INTO STOCK_LEVELS (PRODUCT_ID, WAREHOUSE, QUANTITY) VALUES (1, 'Warehouse A', 150);
INSERT INTO STOCK_LEVELS (PRODUCT_ID, WAREHOUSE, QUANTITY) VALUES (2, 'Warehouse A', 75);
INSERT INTO STOCK_LEVELS (PRODUCT_ID, WAREHOUSE, QUANTITY) VALUES (3, 'Warehouse A', 30);
INSERT INTO STOCK_LEVELS (PRODUCT_ID, WAREHOUSE, QUANTITY) VALUES (4, 'Warehouse B', 5);
INSERT INTO STOCK_LEVELS (PRODUCT_ID, WAREHOUSE, QUANTITY) VALUES (5, 'Warehouse B', 200);

INSERT INTO SUPPLIERS (NAME, CONTACT_EMAIL, PHONE, COUNTRY)
VALUES ('Acme Corp', 'sales@acme.example.com', '555-0100', 'US');
INSERT INTO SUPPLIERS (NAME, CONTACT_EMAIL, PHONE, COUNTRY)
VALUES ('Global Parts', 'info@globalparts.example', '555-0200', 'UK');
INSERT INTO SUPPLIERS (NAME, CONTACT_EMAIL, PHONE, COUNTRY)
VALUES ('QuickSupply', 'orders@quicksupply.example', '555-0300', 'DE');

INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
VALUES (1, TRUNC(SYSDATE) - 10, 29.97, 'completed');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
VALUES (1, TRUNC(SYSDATE) - 3, 99.99, 'completed');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
VALUES (2, TRUNC(SYSDATE) - 5, 49.99, 'shipped');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
VALUES (3, TRUNC(SYSDATE) - 1, 64.96, 'pending');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
VALUES (4, TRUNC(SYSDATE), 9.99, 'pending');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (1, 1, 3, 9.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (2, 4, 1, 99.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (3, 3, 1, 49.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (4, 2, 2, 19.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (4, 5, 1, 14.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (5, 1, 1, 9.99);

INSERT INTO CUSTOMER_SEGMENTS (SEGMENT_NAME, MIN_SPEND, MAX_SPEND, DESCRIPTION)
VALUES ('Bronze', 0, 50, 'New or low-activity customers');
INSERT INTO CUSTOMER_SEGMENTS (SEGMENT_NAME, MIN_SPEND, MAX_SPEND, DESCRIPTION)
VALUES ('Silver', 50.01, 200, 'Regular customers');
INSERT INTO CUSTOMER_SEGMENTS (SEGMENT_NAME, MIN_SPEND, MAX_SPEND, DESCRIPTION)
VALUES ('Gold', 200.01, 1000, 'High-value customers');
INSERT INTO CUSTOMER_SEGMENTS (SEGMENT_NAME, MIN_SPEND, MAX_SPEND, DESCRIPTION)
VALUES ('Platinum', 1000.01, NULL, 'Top-tier customers');

COMMIT;

EXIT;
